"""Core data models, enumerations, and JSON serialization helpers."""

from __future__ import annotations

from insar_prep.core.enums import (
    AoiSource,
    BeamMode,
    CoverageStatus,
    DemDataset,
    JobStatus,
    OrbitDirection,
    Platform,
    Polarization,
    ProductType,
    Provider,
    TargetSoftware,
    TaskStatus,
    TaskType,
    VerticalDatum,
)
from insar_prep.core.error_codes import ERROR_CODE_MESSAGES, ErrorCode
from insar_prep.core.events import Event, EventType
from insar_prep.core.exceptions import (
    AtmosphereProductError,
    ConfigError,
    CredentialError,
    DemProcessingError,
    DownloadError,
    InputValidationError,
    InsarPrepError,
    OrbitMatchingError,
    ProviderError,
    ReportError,
)
from insar_prep.core.logging import (
    configure_global_logging,
    configure_region_logging,
    get_logger,
    log_event,
    mask_secret,
)
from insar_prep.core.models import (
    Aoi,
    AoiBuffer,
    AtmosphericProduct,
    BBox,
    BoundaryCompliance,
    DemProduct,
    DownloadTask,
    InsarBaseModel,
    Job,
    Project,
    Region,
    Scene,
    Workspace,
    generate_id,
)
from insar_prep.core.serialization import (
    load_json,
    model_from_json,
    model_to_json,
    save_json,
)

__all__ = [
    "ERROR_CODE_MESSAGES",
    "Aoi",
    "AoiBuffer",
    "AoiSource",
    "AtmosphereProductError",
    "AtmosphericProduct",
    "BBox",
    "BeamMode",
    "BoundaryCompliance",
    "ConfigError",
    "CoverageStatus",
    "CredentialError",
    "DemDataset",
    "DemProcessingError",
    "DemProduct",
    "DownloadError",
    "DownloadTask",
    "ErrorCode",
    "Event",
    "EventType",
    "InputValidationError",
    "InsarBaseModel",
    "InsarPrepError",
    "Job",
    "JobStatus",
    "OrbitDirection",
    "OrbitMatchingError",
    "Platform",
    "Polarization",
    "ProductType",
    "Project",
    "Provider",
    "ProviderError",
    "Region",
    "ReportError",
    "Scene",
    "TargetSoftware",
    "TaskStatus",
    "TaskType",
    "VerticalDatum",
    "Workspace",
    "configure_global_logging",
    "configure_region_logging",
    "generate_id",
    "get_logger",
    "load_json",
    "log_event",
    "mask_secret",
    "model_from_json",
    "model_to_json",
    "save_json",
]
